# Autoencoders: Dimension Reduction

In [1]:
import numpy as np
from sklearn.datasets import make_blobs

## Data

In [2]:
data = make_blobs(n_samples=25, n_features=3, random_state=123)[0]
data

array([[ 0.78456734,  4.27647404, -3.19856658],
       [ 8.53714456,  4.85977931,  0.1411281 ],
       [ 2.62789474, -2.06978587, -4.94022846],
       [ 4.6759643 , -5.37819856, -6.87327213],
       [ 3.15995024, -3.70046728, -5.33644501],
       [-0.67612822,  5.15702087, -1.16719175],
       [-1.0059971 ,  4.97188769, -2.2590466 ],
       [ 5.59778532, -4.42058578, -6.08216183],
       [ 9.90183603,  4.56431257,  0.88615594],
       [ 9.74032363,  3.49894385, -1.10939689],
       [ 0.68165369,  3.6643471 , -0.49826463],
       [10.85365032,  4.61035172,  0.08490606],
       [11.45964918,  4.39215878, -0.56305117],
       [ 1.17915945, -4.51137085, -6.1589521 ],
       [-0.74783868,  6.75098066, -1.50287771],
       [ 2.31008365, -5.39117772, -5.91041165],
       [ 3.10175474,  4.51713709,  0.26201865],
       [ 4.39502847, -3.55229808, -3.9671444 ],
       [ 9.19302331,  4.70831521, -0.44811939],
       [ 1.30204279,  4.76023172, -0.36356365],
       [11.72312394,  3.46050532, -0.613

## Pre-processing: Normalization

In [3]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
data_scaled = scaler.fit_transform(data)
data_scaled

array([[-0.94576577,  0.6844099 , -0.21643981],
       [ 0.95223768,  0.81644815,  1.05591252],
       [-0.4944782 , -0.75214339, -0.87997577],
       [ 0.00693482, -1.50104293, -1.61642411],
       [-0.36421917, -1.121268  , -1.03092581],
       [-1.30337656,  0.8837324 ,  0.55747061],
       [-1.3841358 ,  0.84182525,  0.14149724],
       [ 0.23261712, -1.2842756 , -1.31502799],
       [ 1.28634453,  0.74956566,  1.33975221],
       [ 1.2468027 ,  0.50840646,  0.57948921],
       [-0.97096132,  0.5458475 ,  0.81231755],
       [ 1.51936985,  0.75998718,  1.03449312],
       [ 1.66773186,  0.71059655,  0.78763526],
       [-0.84916084, -1.30482591, -1.34428344],
       [-1.32093287,  1.24454463,  0.42958142],
       [-0.57228543, -1.50398092, -1.24959484],
       [-0.37846672,  0.73888691,  1.10196923],
       [-0.06184453, -1.0877281 , -0.50925154],
       [ 1.1128114 ,  0.78216241,  0.83142181],
       [-0.81907627,  0.79391434,  0.86363574],
       [ 1.73223635,  0.49970543,  0.768

## Model Building: Autoencoder


In [4]:
input_dim = data_scaled.shape[1]   # 29
input_dim

3

## Model Architecture

In [ ]:
from keras.models import Model
from keras.layers import Input, Dense

Using TensorFlow backend.


In [ ]:
encoding_dim = 2

input_layer = Input(shape=(input_dim, ))
encoder = Dense(encoding_dim)(input_layer)
decoder = Dense(input_dim)(encoder)

autoencoder = Model(inputs=input_layer, outputs=decoder)

autoencoder.summary()




Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 3)                 0         
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 6         
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 6         
Total params: 12
Trainable params: 12
Non-trainable params: 0
_________________________________________________________________


## Compiling and Fitting the model

In [ ]:
autoencoder.compile(optimizer='adam', 
                    loss='mean_squared_error')

In [ ]:
autoencoder.fit(data_scaled, data_scaled,       
                    epochs=7000,
                    shuffle=True,
                    verbose=1)




Epoch 1/7000





25/25 [==============================] - 1s 48ms/step - loss: 5.3560
Epoch 2/7000
25/25 [==============================] - 0s 264us/step - loss: 5.3319
Epoch 3/7000
25/25 [==============================] - 0s 199us/step - loss: 5.3079
Epoch 4/7000
25/25 [==============================] - 0s 171us/step - loss: 5.2840
Epoch 5/7000
25/25 [==============================] - 0s 174us/step - loss: 5.2603
Epoch 6/7000
25/25 [==============================] - 0s 133us/step - loss: 5.2366
Epoch 7/7000
25/25 [==============================] - 0s 278us/step - loss: 5.2130
Epoch 8/7000
25/25 [==============================] - 0s 203us/step - loss: 5.1896
Epoch 9/7000
25/25 [==============================] - 0s 213us/step - loss: 5.1663
Epoch 10/7000
25/25 [==============================] - 0s 227us/step - loss: 5.1431
Epoch 11/7000
25/25 [==============================] - 0s 221us/step - loss: 5.1200
Epoch 12/7000
25/25 [==============================] - 0s 185us/step - loss: 5

## Model Prediction

In [ ]:
autoencoder.predict(data_scaled)

array([[-1.0284756 ,  0.39649194,  0.09379404],
       [ 0.95843285,  0.8380141 ,  1.0326748 ],
       [-0.50145495, -0.7764296 , -0.8538073 ],
       [-0.02424036, -1.6095649 , -1.4994913 ],
       [-0.34956437, -1.0702538 , -1.0858942 ],
       [-1.2916535 ,  0.9245406 ,  0.5135001 ],
       [-1.4214842 ,  0.7118134 ,  0.28158653],
       [ 0.2069896 , -1.3734862 , -1.2189034 ],
       [ 1.3279884 ,  0.8945306 ,  1.1835513 ],
       [ 1.2158537 ,  0.40067154,  0.695574  ],
       [-0.8930374 ,  0.8171049 ,  0.5200364 ],
       [ 1.5089864 ,  0.72384197,  1.0734395 ],
       [ 1.6241497 ,  0.5588848 ,  0.95110524],
       [-0.836424  , -1.2604879 , -1.3920579 ],
       [-1.3724008 ,  1.0653809 ,  0.6226321 ],
       [-0.5311667 , -1.360844  , -1.4038258 ],
       [-0.30706418,  0.9874429 ,  0.8341489 ],
       [ 0.00939201, -0.8397496 , -0.7764502 ],
       [ 1.0865121 ,  0.6906131 ,  0.9300666 ],
       [-0.77140933,  0.959845  ,  0.68484473],
       [ 1.7106295 ,  0.42449105,  0.849

In [ ]:
np.round(autoencoder.predict(data_scaled),4)

array([[-1.0285,  0.3965,  0.0938],
       [ 0.9584,  0.838 ,  1.0327],
       [-0.5015, -0.7764, -0.8538],
       [-0.0242, -1.6096, -1.4995],
       [-0.3496, -1.0703, -1.0859],
       [-1.2917,  0.9245,  0.5135],
       [-1.4215,  0.7118,  0.2816],
       [ 0.207 , -1.3735, -1.2189],
       [ 1.328 ,  0.8945,  1.1836],
       [ 1.2159,  0.4007,  0.6956],
       [-0.893 ,  0.8171,  0.52  ],
       [ 1.509 ,  0.7238,  1.0734],
       [ 1.6241,  0.5589,  0.9511],
       [-0.8364, -1.2605, -1.3921],
       [-1.3724,  1.0654,  0.6226],
       [-0.5312, -1.3608, -1.4038],
       [-0.3071,  0.9874,  0.8341],
       [ 0.0094, -0.8397, -0.7764],
       [ 1.0865,  0.6906,  0.9301],
       [-0.7714,  0.9598,  0.6848],
       [ 1.7106,  0.4245,  0.8495],
       [-0.3452, -1.4271, -1.4157],
       [-0.1412, -1.756 , -1.6664],
       [ 1.1085,  0.5008,  0.7599],
       [-0.9427,  0.5793,  0.2863]], dtype=float32)